config/routes.rb
Rails.application.routes.draw do
  resources :chapters do
    resources :sections
  end

  resources :sections do
    resources :lessons
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  has_many :sections
  validates :name, :presence => true

  scope :most_sections, -> {(
    select("chapters.name, count(sections.id) as sections_count")
    .joins(:sections)
    .group("chapters.id")
    .order("sections_count DESC")
    .limit(3)
    )}
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  validates :name, :presence => true
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :lessons
  belongs_to :chapter
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

  def index
    @chapters = Chapter.all
    render :index
  end

  def new
    @chapter = Chapter.new
    render :new
  end

  def show
    @chapter = Chapter.find(params[:id])

    render :show
  end

  def create
    @chapter = Chapter.new(chapter_params)
    if @chapter.save
      redirect_to chapters_path
    else
      render :new
    end
  end

  def edit
    @chapter = Chapter.find(params[:id])
    render :edit
  end

  def update
   @chapter = Chapter.find(params[:id])
   if @chapter.update(chapter_params)
     redirect_to chapters_path
   else
     render :edit
   end
  end

  def destroy
    @chapter = Chapter.find(params[:id])
    @chapter.destroy
    redirect_to chapters_path
  end
end

private
  def chapter_params
    params.require(:chapter).permit(:name)
  end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def index
    @lessons = Lesson.all
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    @chapter = Chapter.find(params[:chapter_id])
    @section = Section.find(params[:section_id])
    @lesson = @chapter.section.lesson.new
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController


    def index
      @sections = Section.all
      render :index
    end

    def new
      @chapter = Chapter.find(params[:chapter_id])
      @section = @chapter.sections.new
      render :new
    end

    def show
      @section = Section.find(params[:id])
      render :show
    end

    def create
      @chapter = Chapter.find(params[:chapter_id])
      @section = @chapter.sections.new(section_params)
      if @section.save
        flash[:notice] = "Section successfully added!"
        redirect_to chapter_path(@section.chapter)
      else
        render :new
      end
    end

    def edit
      @section = Section.find(params[:id])
      render :edit
    end

    def update
     @section = Section.find(params[:id])
     if @section.update(section_params)
       redirect_to sections_path
     else
       render :edit
     end
    end

    def destroy
      @section = Section.find(params[:id])
      @section.destroy
      redirect_to chapter_path(@section.chapter)
    end
end

  private
    def section_params
      params.require(:section).permit(:name)
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chapters/_form.html.erb
<%= render "layouts/errors", :object => @chapter %>

<%= form_for @chapter do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/chapters/edit.html.erb
<h1>Edit this Chapter Name</h1>

<%= render "form" %>

app/views/chapters/index.html.erb
<h1>Courses</h1>

<ul>
  <% @chapters.each do |chapter| %>
  <li><%= link_to chapter.name, chapter_path(chapter) %></li>
  <% end %>
</ul>

<%= link_to "New Chapter", new_chapter_path %>

app/views/chapters/new.html.erb
<h1>Add a new Chapter</h1>

<%= render "form" %>

app/views/chapters/show.html.erb
<h2><%= @chapter.name %> </h2>


<% if @chapter.sections.any? %>
<h4>Section<% @chapter.name %></h4>
  <ul>
    <% @chapter.sections.each do |section| %>
    <li>
      <%= link_to section.name %> |
      <%= link_to "Edit Section", edit_chapter_section_path(@chapter, section) %> |
      <%= link_to "Delete", chapter_section_path(@chapter, section),
                                        :data => {:confirm => "Are you sure?",
                                          :method => "delete"} %>

    </li>
    <% end %>
  </ul>
  <% else %>
  <p>
    No Chapters yet
  </p>
  <% end %>

  <p><%= link_to "Add a section", new_chapter_section_path(@chapter) %></p>
<p><%= link_to "Delete Chapter", chapter_path(@chapter),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to Chapters", chapters_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rebuild</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="navbar-class">
  <div class="container">


  <!-- Collect the nav links, forms, and other content for toggling -->

    <ul class="nav navbar-nav">

      <li><%=link_to "Chapters", chapters_path%></li>
      <li><%=link_to "Sections", sections_path %></li>
    </ul>


  </div>
</div>

  <body>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/lessons/index.html.erb
<h1>Lesson Test</h1>

<ul>
  <% @lessons.each do |lesson| %>
  <li><%= link_to lesson.name, lesson_path(lesson) %></li>
  <% end %>
</ul>

<%= link_to "New Section", new_lesson_path %>

app/views/lessons/show.html.erb
<h1><%= @lesson.name %></h1>

app/views/sections/_form.html.erb
<%= render("layouts/errors", :object => @section, ) %>

<%= form_for [@chapter, @section] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/sections/edit.html.erb
<h1>Edit Section</h1>

<%= render "form" %>

app/views/sections/index.html.erb
<h1 class="well">Sections</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><% @sections.each do |section| %></th>
      <th class="list"><%= link_to section.name, section_path(section) %></th>
      <% end %>
    </tr>
  </thead>
</table>

app/views/sections/new.html.erb
<h1>Add New Section</h1>

<%= render "form"  %>

app/views/sections/show.html.erb
<h1>
  <%= @section.name %></h1>
<h2>Relationship in Rails</h2>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

<% if @section.lessons.any? %>
<h4>Sections<% section.name %></h4>
  <ul>
    <% @section.lessons.each do |section| %>
    <li>
      <%= link_to section.name %>
    </li>
    <% end %>
  </ul>
  <% else %>
  <p>
    No Sections yet
  </p>
  <% end %>

<p><%= link_to "Return to Sections", sections_path %></p>